### ISSUE TITLE
Clear serial output text area through serial command

### ISSUE THREAD

**Issue by vincentchu12** [kammce/Telemetry#28]

**Comment by kammce** [comment]
Using this as a reference: http://www.termsys.demon.co.uk/vtansi.htm

The telemetry terminal should be able to interpret the **<ESC>[2J** signal and clear the terminal when it appears.

**Comment by kammce** [comment]
This will be closed when #26 is closed.

**Comment by kammce** [comment]
Thanks @evanugarte for fixing this issue with pull request #33 
@vincentchu12
